### ISSUE TITLE
the ability to work with multiple desktops VDI

### ISSUE THREAD

**Issue by Dmitry5755** [Seitanas/kvm-vdi#130]
Hello!
When I connect from the Linux client to the machine, for example, to Windows 10, I no longer have the option to exit the desktop or minimize it. This would give me the opportunity to connect to other virtual machines other hypervisors. Is it possible at all? Or is the main purpose of working on VDI in one desktop environment for the average user? This of course can be done using the help of the remote viewer, but each time you have to look for a password from the database on the hypervisor. And one more question: I am getting the USB connection only when I connect through the remote viewer. Through the console using the command /usr/local/VDI-client/kvm-vdi-client, does not work

**Comment by Seitanas** [comment]
Hello,
the main purpose of `KVM-VDI` is to provide `VDI` solution for thin clients. You cannot use multiple `VDI` environments simultaneously,  - there can be only one running `VDI` on a single client at a time.
Taking password from DB and feeding it to spice client will do nothing good, because `kvm-vdi-client` sends heartbeats to `KVM-VDI` infrastructure. If heartbeats stop for a defined period of time, - VM is marked as to be destroyed, and any other client connecting to KVM-VDI will at some point destroy it and reuse.  

As for usb connection - if `kvm-vdi-client` uses the same `remote-viewer` binary, it should also work as `kvm-vdi-client` does not modify any `remote-viewer` USB parameters.

**Comment by Dmitry5755** [comment]
Thank you
