### ISSUE TITLE
Security issues.

### ISSUE THREAD

**Issue by theblazehen** [Seitanas/kvm-vdi#38]
Hi.

I found some pretty major security issues (plural), who can I contact to get them fixed / can someone contact me?

**Comment by henickr** [comment]
this is the type of thing they probably don't want in open forum so thanks for your discretion.  looks like the developer may be on vacation because he hasn't answered in a few days and is usually very quick to respond to me.  I don't want to include his email in open forum like that so email me at raymond.henick-at-dal.ca and I will send you his direct email so you can speak to him about them without including me as i am not on the project team i am just a user like yourself.

thanks.

**Comment by Seitanas** [comment]
Hello, you can contact me by mail tadas at ring.lt
