### ISSUE TITLE
enhancement request: checkboxes on VDI header for snapshot and maintenance

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#44]
When you 'populate machines' after modifying your initial image, all machines get put into maintenance mode by design.  This is good but it also automatically turns off snapshots.

Let's say you have 20 machines in a VDI pool and you push a new application to the initial image, normally you have a single operation to worry about but instead you have to 'populate' then proceed to click 40 times to take them all out of maintenance then turn snapshot back on.

Might be a more efficient way to do that if the header had a select all option... like gmail.

**Comment by Seitanas** [comment]
That's why you have `Turn maintenance off` button in your initial image dropdown. It will mass-turnoff maintenance for all child VMs
![](https://camo.githubusercontent.com/7b66aab537fba12d0c2c48ec63c1541c0e1d53fb/687474703a2f2f7765626a61696c2e72696e672e6c742f7664692f766469322e6a70673f7261773d747275652631)

**Comment by henickr** [comment]
sorry next time i'll open my eyes!  you're ahead of me this time.  ;)

**Comment by henickr** [comment]
oh yeah these options are great.  i've been using a for loop with virsh commands.  

maybe you should point these out somewhere... i know they're right in your face but i honestly didn't notice 'em.  unless they're new and thats why i didn't.... maybe i'm blind...
