### ISSUE TITLE
installing kvm-vdi on osx

### ISSUE THREAD

**Issue by mrjosh** [Seitanas/kvm-vdi#51]
hello there,
how can i install on osx ?

**Comment by henickr** [comment]
you'd be looking for running qemu-kvm on osx and i'm not sure i've seen that before.
this software requires qemu-kvm to be installed in order to function...

in theory i guess it is possible but you would be in for a lot of work i think because any documentation you look for would be riddled with people trying to do the opposite.... run osx on qemu-kvm.

so it would be a needle in a haystack looking for help... if its even possible.  
debian unstable and fedora currently run qemu-kvm best.... so bsd... i don't want to say no... 
but good luck :)

**Comment by mrjosh** [comment]
thanks a lot
