### ISSUE TITLE
enhancement request: starred/locked image... or backup function.

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#52]
Hi, I have what I feel is an important enhancement.  Correct me if I'm wrong but this is how I've been organizing images.  Source image is just that, fresh and new in case you need it.  Initial image is where you make all of your customization for the iso before you deploy them to a vdi pool.

So all the changes are in domain-initial.  There is an easy option there to copy from source that could blow away all of your changes too easily for my comfort.  Maybe make it so you can either star or lock initial images so they can't be copied over without at least acknowledging doing so ... or back to the admin thing I suggested in another request would also work, so only admins could do this.

Failing star or lock function... a backup function that could just freeze vm then make a quick copy in a safe place.  Initial images can have a lot of work go into them.  It couldn't hurt to have something protect them.

**Comment by Seitanas** [comment]
Well, in fact you install all features and customizations in the `Source` image. The idea of `Initial` image is that you will be able to install new features without affecting your VDI vms, because you will install them to `Source` image and copy it over `Initial` only after you are satisfied with everything. This saves time. Also, `Initial` machine is where you run all your sysprep scripts (remove computer name, make system name itself and join domain on next reboot etc).
But I'm also having the same problem, where you can affect all your VDI machines by accidentally copying Source over Initial. I was planing to make Initial VM inactive as soon as you make child VMS from it.
