### ISSUE TITLE
enhancement request: convert .vdi to qcow2

### ISSUE THREAD

**Issue by henickr** [Seitanas/kvm-vdi#55]
Hi, I am not sure if this is something that would be useful for everybody but let me know what you think.  We have a few professors who submit their own custom vdi images for the class they are going to teach so this requires running of the command 
qemu-img convert -f vdi ThorV1_3.vdi -O qcow2 ThorV1_3.qcow2

This seems to work ok.  (on first look --- still untested thoroughly) I was wondering if you could add something in the 'create_vm.php' file that did the conversion automatically if the iso chosen had the extension .vdi instead.  Instead of creating an empty image and mounting the iso as a drive, it could create an image based on the vdi one provided then link the system directly to that qcow2 file instead of the typical 'install' procedure.

maybe a button to 'upload image' would be useful so you can upload directly from the web interface into /var/lib/libvirt/images (wherever that points to) for deploy to wherever it is mounted.  this upload function could automatically convert anything possible to qcow2 if not a bootable iso.  (unless there is another way to do this, i currently usually wget it and/or scp to get it there)

edit: I'm actually testing this manually now to see how well it actually works and having a bit of difficulty so it may not be feasible.  will update again when i have more info.

Thanks.

**Comment by Seitanas** [comment]
Hello,
no, I don't think it's a good idea for a conversion at this stage.
First of all, ISO is just an install image, which is booted and produces install capabilities for your VM.
.vdi file, on the other hand (I presume one is using Virtualbox to make VM images) is a standalone VM disk. This means, that you need to upload image, convert it to qemu-readabe format ant then mount it to some VM. 
Having said that, - you will encounter problems with mismatching devices between Virtualbox and qemu (Virtualbox uses different kind of network/storage/etc controllers). 
And even if it will probably work with Linux guests, it will fail to boot Windows ones (even after you convert vdi to qcow), because you will still have different emulator with different controllers.
I think it's better to provide professors with a login and a pool with source or initial images and allow them to install their OS and software via KVM-VDI (this capability will be released soon).

**Comment by henickr** [comment]
now you know where that idea came from too :)  glad you liked it... ok thanks... i'm still going to test conversion a bit and see if i can make anything cool happen but as you said, it isn't all that smooth

**Comment by henickr** [comment]
oh, all conversion aside... 
the upload image page would still be cool to avoid the wget/scp to the image location.  

a bit more thinking if not using a shared area as an image dump mounted on each hypervisor though... maybe mitigated by a db table pointing to physical locations controlled by checkboxes

**Comment by henickr** [comment]
ok and another idea also.... this granulated admin structure is much better than conversion imo.... 

hypothetically a student still wants to work in virtualbox rather than connecting their laptop via virt-viewer to the spice session.  (not sure why anyone would want that but its possible for whatever reason) .... obviously virt-viewer is preferable here if they have an internet connection

maybe you could have a 'download virtualbox image' or 'download qemu image' link (maybe beside the tiny little soft/hard power downs on the pool icon) that allowed the user of the image to download a copy in the requested format via httpd for local use...

not a required thing obviously but it could be used to add a bit of freedom of choice for the user...  
as to the mismatched devices... well that would be their problem if they wanted to use it.  from what i can tell, its the same balloon/nic/storage driver so windows handles it ok in my tests.

anyway, just an idea... ignore me if you want.  :)
