### ISSUE TITLE
 can multiple users concurrent connect to a single vm?

### ISSUE THREAD

**Issue by brike** [Seitanas/kvm-vdi#73]
if there is a solution that user A,user B,and C can accese via spice_html5 in the same time?

**Comment by Seitanas** [comment]
No, SPICE protocol cannot serve more than one instance.

**Comment by henickr** [comment]
They can take over a vm previously in use  by someone else though if that
helps.  Not at the same time.

On Nov 23, 2016 11:32 AM, "Tadas Ustinavičius" notifications@github.com
wrote:

No, SPICE protocol cannot serve more than one instance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/Seitanas/kvm-vdi/issues/73#issuecomment-262547617, or mute
the thread

**Comment by Seitanas** [comment]
They should not take over. Only the same user is able to take over his machine (if clicking  a  pool from another location).
VM is reserved to particular user for a `$return_to_pool_after` period (in minutes). Only after user is disconnected for that period of time, machine is returned to pool. Also it will be reset if provided to new user and if  `$reset_vm=1;`
I guess the question is for some kind conference idea, where multiple users are allowed to see and control the same desktop. So no - this is not possible due limitations in SPICE.
