### ISSUE TITLE
the performance via spice-html5 is too bad...

### ISSUE THREAD

**Issue by brike** [Seitanas/kvm-vdi#74]
It says “for a normal 1080p session the performance is very good up to 150-200ms of latency and 100kb/s bandwidth”，but i get almost 2000ms of latency，how to improve it？

**Comment by Seitanas** [comment]
SPICE-HTML5 feature is still in alpha release. You should use kvm-vdi-client for production.

**Comment by henickr** [comment]
this isn't really something that the developer can help you with because it isn't an issue with his software but i would suggest you check your resources first to make sure none are pinned at 100% and then start checking the pathways in the following way

external client -> 80/449/5959 (dashboard) -> 5900-59xx (from dashboard to hypervisor node)
i suspect it is a resource problem because it works at all.  try installing iotop if you're using spindle devices.  if you start up 10 vms on a spindle it can take a few minutes before i/o normalizes and the vms become usable.

hth
