### ISSUE TITLE
KVM-VDI client area SPICE console 

### ISSUE THREAD

**Issue by Gokev79** [Seitanas/kvm-vdi#86]
Is it possible to use/configure the spice console and not the HTML5 console inside the client area?

**Comment by Seitanas** [comment]
You will automatically use SPICE client when using kvm-vdi thin client application. If you access client area via browser - then you will be automatically provided with HTML5 client.

**Comment by Gokev79** [comment]
Yes I now.  
But I want use the client area via browser, but with the SPICE client (html5 is slow). 

It would be useful if you have a choice inside the client area via browser. ;-)

**Comment by Seitanas** [comment]
There is no available solution for this because of architecture of KMV-VDI and the needing for client to send heartbeats to server. Thus for SPICE client you need to use GTK frontend.

**Comment by Gokev79** [comment]
I thought it might be easy to do. Because you have the choice in the admin section.
Too bad that it can not. But thanks for your reply.

**Comment by Seitanas** [comment]
SPICE console from admin panel takes machines directly. Not from pool. This means, that its possible for this channel to be overtaken by client, - if KVM-VDI decides to provide that machine for him and machine is not in maintenance mode.

When user accesses machine via client area, KVM-VDI must receive heartbeats from client to know, that the machine is still in use. Having web portal + non-HTML5 client will abuse this, because when browser window is closed, client will still have his console via SPICE client, but will send no heartbeats.

**Comment by Gokev79** [comment]
I understand why it's not possible.
